name: Release Desktop App

on:
  push:
    tags:
      - 'v*' # Déclenché quand vous poussez un tag comme v1.0.1

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          npm ci

      - name: Build Tauri app
        run: npm run tauri:build

      - name: Generate latest.json
        shell: pwsh
        run: |
          # Arrêter en cas d'erreur
          $ErrorActionPreference = "Stop"
          
          # Extraire la version depuis le tag
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          Write-Host "========================================" -ForegroundColor Cyan
          Write-Host "Version détectée: $version" -ForegroundColor Cyan
          Write-Host "========================================" -ForegroundColor Cyan
          
          # Chemin de l'installateur
          $exePath = "src-tauri\target\release\bundle\nsis\Formalyse_${version}_x64-setup.exe"
          
          # Vérifier que le fichier existe
          if (-not (Test-Path $exePath)) {
            Write-Error "Fichier introuvable: $exePath"
            exit 1
          }
          Write-Host "✓ Installateur trouvé: $exePath" -ForegroundColor Green
          
          # URL de téléchargement
          $downloadUrl = "https://github.com/${{ github.repository }}/releases/download/v${version}/Formalyse_${version}_x64-setup.exe"
          
          # Date actuelle
          $pubDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
          
          # Créer latest.json SANS signature (sécurisé par HTTPS)
          $latestJson = @{
            version = $version
            notes = "Release version $version"
            pub_date = $pubDate
            platforms = @{
              "windows-x86_64" = @{
                url = $downloadUrl
              }
            }
          } | ConvertTo-Json -Depth 10
          
          # Sauvegarder sans BOM
          $latestJson | Out-File -FilePath "latest.json" -Encoding utf8NoBOM
          
          Write-Host "========================================" -ForegroundColor Green
          Write-Host "latest.json créé avec succès !" -ForegroundColor Green
          Write-Host "========================================" -ForegroundColor Green
          Write-Host ""
          Write-Host "Contenu de latest.json:" -ForegroundColor Cyan
          Get-Content "latest.json" | Write-Host

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/nsis/Formalyse_*_x64-setup.exe
            latest.json
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

